# Generated by Django 4.1.1 on 2022-09-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snickersMarket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manufacturer2',
        ),
    ]
