# Generated by Django 4.1.1 on 2022-09-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snickersMarket', '0003_alter_manufacturer_name_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='asd', upload_to=''),
        ),
    ]
