# Generated by Django 4.1.1 on 2022-09-23 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snickersMarket', '0005_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('color', models.CharField(default='', max_length=15)),
                ('size', models.CharField(default='', max_length=5)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snickersMarket.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
