# Generated by Django 4.1.1 on 2022-09-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snickersMarket', '0006_bagelement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bagelement',
            old_name='product_type',
            new_name='product',
        ),
    ]
