# Generated by Django 4.1.1 on 2022-09-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snickersMarket', '0007_rename_product_type_bagelement_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/defaultImage.jpg', upload_to=''),
        ),
    ]
