# Generated by Django 4.1.1 on 2022-09-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snickersMarket', '0008_product_brand_product_model_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pre_order',
            field=models.IntegerField(default=0),
        ),
    ]
