# Generated by Django 4.1.1 on 2022-09-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snickersMarket', '0009_product_pre_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/defaultImage.jpg', upload_to='static/images/'),
        ),
    ]
