# Generated by Django 3.2.12 on 2022-07-13 23:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('title', models.CharField(max_length=50, verbose_name='Должность')),
                ('on_vacation', models.BooleanField(default=False, verbose_name='В отпуске')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Тэг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание задачи')),
                ('date_of_creation', models.DateTimeField(default=datetime.datetime(2022, 7, 13, 23, 0, 49, 896563, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskstodo.author')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskstodo.tag')),
            ],
        ),
    ]
